### ISSUE TITLE
其他方式布局

### ISSUE THREAD

**Issue by maxwell44** [iAlexSun/ASXcodeSourceExtensioin#1]
个人在项目中不是很习惯用Masory，不知道是否可以添加 PureLayout 一类的

**Comment by iAlexSun** [comment]
之后可能会修改成用户可以自定义的类型

**Comment by iAlexSun** [comment]
> 个人在项目中不是很习惯用Masory，不知道是否可以添加 PureLayout 一类的

增加了用户可以自定义规则,使用时只要上传自己定义好的plist文件即可
